config/routes.rb
Rails.application.routes.draw do




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    collection do
      get :taketexts
      #自分の受け取ったletter一覧を取得
      get :givetexts
      #自分が送ったletter一覧を取得
      get :takeusers
      #自分がletterを送ったuserの一覧を取得する
    end
  end
  
  resources :postletters, only: [:create, :destroy, :update, :edit]
  resources :secrets, only: [:create, :destroy, :update, :edit]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'passwordlogin', to: 'passwordlogin#new'
  post 'passwordlogin', to: 'passwordlogin#create'
  
  get 'users/:id/new', to: 'users#new', as: 'sign'
  get 'sessions/:id/new', to: 'sessions#new', as: 'loginsession'
  
  
  resources :enjoy, only: [:index]
  resources :enjoy2, only: [:index]
  resources :enjoy3, only: [:index]
  resources :enjoy4, only: [:index]
  resources :enjoy5, only: [:index]
  resources :enjoy6, only: [:index]
  
  resources :choice, only: [:index, :show]
  resources :lies, only: [:index, :show]
  resources :truths, only: [:index, :show]
  resources :trueletter, only: [:show]
  resources :ookamiletter, only: [:show]
  resources :ookamiproduction, only: [:show]
  resources :trueproduction, only: [:show]
  resources :ookamigaide, only:[:index, :show]
  resources :truegaide, only:[:index, :show]
  resources :sendgaideletter,only:[:index, :show]
  resources :secret, only:[:index, :show]
  resources :looksecret, only:[:index, :show]
  resources :back, only:[:index]
  resources :friends, only:[:index, :show, :create, :destroy]
  resources :friendcreate, only:[:index, :show]
  resources :friendcamera, only:[:index, :show]
  resources :profileedit, only:[:index, :show]
  resources :passfinish, only:[:index,:show]
  resources :takeletters, only: [:index, :show, :edit]
  resources :lookfriend, only:[:index,:show]
  resources :fromthink, only:[:index,:show, :create]
  resources :thinks, only:[:create]
  resources :thinkfinish, only:[:index,:show]
  resources :ask, only:[:index]
  resources :recoms,only:[:index, :show, :create]
  resources :recomfinish, only:[:show]
  resources :takethink, only:[:index, :show]
  resources :takerecom, only:[:index, :show]
  resources :letterfinish, only:[:index,:show]
  resources :ookamifinish, only:[:index,:show]
  resources :takedthink, only:[:show,:edit]
  resources :takedrecom, only:[:show,:edit]
  resources :responses, only:[:index, :show, :create, :destroy, :update, :edit ]
  resources :letsletter,only:[:index, :show]
  resources :toletter,only:[:show, :index]
  resources :changeletters, only:[:index, :show, :create, :destroy, :update, :edit ]
  resources :lookletter, only:[:show]
  resources :reply,only:[:show, :index]
  resources :lettersended, only:[:show]
  resources :newletter, only:[:show]
  resources :fromletter, only:[:show]
  resources :takesendgaide,only:[:show]
  resources :gaideaccount, only:[:index]
  resources :lettergaide,  only:[:show]
  resources :gaide1, only:[:index]
  resources :gaide2, only:[:index]
  resources :gaide3, only:[:index]
  resources :delete, only:[:index]
  resources :questionsend, only:[:show]
  resources :notice1, only:[:show]
  resources :notice2, only:[:show]
  resources :notice3, only:[:show]
  resources :notice4, only:[:show]
  resources :notice5, only:[:show]
  resources :notice6, only:[:show]
  resources :notice7, only:[:show]
  resources :notice8, only:[:show]
  resources :notice9, only:[:show]
  resources :notice10, only:[:show]
  resources :notice11, only:[:show]
  resources :notice12, only:[:show]
  resources :notice13, only:[:show]
  resources :choicequestion, only:[:show]
  resources :laughquestion, only:[:show]
  resources :lifequestion, only:[:show]
  resources :notice14, only:[:show]
  resources :notice15, only:[:show]
  resources :notice16, only:[:show]
  resources :notice17, only:[:show]
  resources :notice18, only:[:show]
  resources :notice19, only:[:show]
  resources :notice20, only:[:show]
  resources :notice21, only:[:show]
  resources :notice22, only:[:show]
  resources :notice23, only:[:show]
  resources :notice24, only:[:show]
  resources :notice25, only:[:show]
  resources :notice26, only:[:show]
  resources :notice27, only:[:show]
  resources :notice28, only:[:show]
  resources :notice29, only:[:show]
  resources :notice30, only:[:show]
  resources :notice31, only:[:show]
  resources :notice32, only:[:show]
  resources :notice33, only:[:show]
  resources :notice34, only:[:show]
  resources :notice35, only:[:show]
  resources :notice36, only:[:show]
  resources :notice37, only:[:show]
  resources :notice38, only:[:show]
  resources :notice39, only:[:show]
  
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
  validates :sentence, presence: true, length: { maximum: 90 }
  validates :person,presence: true,length: { maximum: 15 }
  #sentenceの上限は90文字まで
  
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  
  
  
  def create
    
    
    @friend = current_user.friends.build(friend_params)
    #current_userが勝手にuser_idに代入される
    if @friend.save
      
      redirect_to friendcamera_path(@friend)
      #現在のfriendの数字が渡される
    else
      flash[:danger] = '文章は90文字以内また人物名が15文字以内にしてください'
      redirect_to friendcreate_path(@friend.user_id)
    end
    
  end

  def destroy
    @friend = current_user.friends.find_by(id: params[:id])
    
    unless @friend
      redirect_to root_path
    end
    
    @friend.destroy
    redirect_to friends_path
    
  end
  
  def show
    @friend = Friend.find(params[:id])
  end

  def index
    if logged_in?
      @myuser=current_user
      @friend=current_user.friends.build
      @friends = Friend.where(user_id: current_user.id).order(id: "DESC")
      #user_idが自分のidのやつだけを取得
    end
  end
  
  private
  
  def friend_params
    params.require(:friend).permit(:sentence, :person)
  end

  
end

app/helpers/friend_helper.rb
module FriendHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/index.html.erb
<div class="backbutton">
  <%= link_to root_path ,class: 'takebuttonhidden' do %>
    <%= image_tag "/newimages/backbutton@2x.png",:size =>"19x33" %>
  <% end %>
</div>

<div class="letter-log">
  <img src="/newimages/friendtitle@2x.png" alt="友達紹介" width="235px" height="66px" class="friend-logo">
</div>

<div class="friendbutton">
  <%= link_to friendcreate_path(@myuser) ,class: 'takebuttonhidden' do %>
    <%= image_tag "/newimages/addletter@2x.png",:size =>"118x100" %>
  <% end %>
</div>

<div class="whitebox col-md-offset-2 col-md-8 col-sm-offset-2 col-sm-8">
  <ul class="media-list">
    <% @friends.each do |friend| %>
    
      
       <li class="friend">
          <div class="media-main">
              
              <div class="name">
                <%= link_to friend_path(friend) ,class: 'takebuttonhidden', :style=>"color:black;" do %>
                  <p class="nametext"><%= friend.person %></p>
                <% end %>
              </div>
              
              <%= link_to ' ', friend_path(friend) ,class: 'friendtext' %>
              
          </div>
      </li>
      
    <% end %>
    
  </ul>
</div>

<div class="friend-gaide">
  <img src="/newimages/friendgaides@2x.png" alt="友達紹介ガイド" width="309px" height="361px" class="friend-logo">
</div>

app/views/friends/show.html.erb
<% if current_user == @friend.user %>
<!--ログインしているユーザーと一致したら-->
<div class="backbutton">
  <%= link_to :back ,class: 'takebuttonhidden' do %>
    <%= image_tag "/newimages/backbutton@2x.png",:size =>"19x33" %>
  <% end %>
</div>
  <!--自分のフレンドshowしか見れない-->
<div class="deletebutton">
  <%= link_to  @friend, method: :delete, data: { confirm: "紹介文を削除しますか?" }, class: 'deletes' do %>
    <%= image_tag "/newimages/friend-deletes@2x.png",:size =>"33x33" %>
  <% end %>
</div>

<% else %>

<div class="backbutton">
  <%= link_to lookfriend_path(@friend.user) ,class: 'takebuttonhidden' do %>
    <%= image_tag "/newimages/backbutton@2x.png",:size =>"19x33" %>
  <% end %>
</div>

<% end %>



<div class="friend-title">
  <img src="/newimages/personimae@2x.png" alt="友達紹介" width="338px" height="111px" class="friend-logo">
</div>



<%= form_for(@friend) do |f| %>
   <% if @friend.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @friend.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="letterarea">
    <div class="form-group">
        
    <%= f.text_area :person, class: 'form-person', rows: 5, readonly: true %>
    <div class="letter-line">
      <img src="/newimages/personline@2x.png" alt="友達紹介" width="198px" height="3px" class="friend-logo">
    </div>
    <div class="textback">
      <%= f.text_area :sentence, class: 'form-control', rows: 5, readonly: true %>
    </div>
    
    
    <!--隠しフィールド内に値をセットする場合はvalueオプションを使用する必要がある-->
  </div>
</div>

<% end %>

<div class="friendbaton">
  <img src="/newimages/friendbaton@2x.png" alt="友達紹介リレー" width="320px" height="135px" class="friend-logo">
</div>